### ISSUE TITLE
Trexp - allow symbolic use

### ISSUE THREAD

**Issue by Maltergate** [petercorke/spatial-math#13]
I sometime compute symbolical expression of jacobians of functions using `trexp`. The line 108 causes an error as it is a comparison with numerical value (<10*eps).

I personally changed in my version including `~isa(w, 'sym')`, to allow symbolical use of the function `trexp` and I though it might be nice to include it in the general repository.

Side not: this extra care is given in the function `trlog`.

Thanks.

**Comment by petercorke** [comment]
Thanks for flagging this.  Symbolic support is still not complete.  At the moment my development time is going into the Python version of this Toolbox, and SymPy is doing a pretty good job.  Please feel free to submit a pull request.
